kind: pipeline
name: default

clone:
  depth: 50

steps:
  - name: download-dependency
    image: golang:1.16
    commands:
      - go mod download

  - name: test
    image: golang:1.16
    commands:
      - go test ./ -v -cover

  - name: build
    image: golang:1.16
    commands:
      - go build
      - ls

  - name: run
    image: golang:1.16
    commands:
      - ./fizzbuzz